- hosts: all
  gather_facts: no
  remote_user: "{{ hosts_remote_user  }}"

  vars:
    app_port: 80
    pip_install_packages: 
      - name: docker 
        version: 6.1.3
  
  roles:
    - { role: geerlingguy.pip, become: yes }
  
  tasks:
    - ansible.builtin.template:
        src: .env.j2
        dest: .env

    - name: Run app
      community.docker.docker_container:
        name: redmine_app
        image: redmine:5.0.5
        published_ports:
          - "{{ app_port }}:3000"
        restart_policy: always
        env_file: .env