- hosts: all
  remote_user: "{{ hosts_remote_user }}"

  vars:
    pip_install_packages: 
      - name: docker 
        version: 6.1.3
  
  roles:
    - { role: geerlingguy.pip, become: yes }
  
  tasks:
    - ansible.builtin.template:
        src: .env.j2
        dest: .env

    - name: Run app
      community.docker.docker_container:
        name: redmine_app
        image: redmine:5.0.5
        published_ports:
          - "{{ app_port }}:3000"
        restart_policy: always
        env_file: .env

- hosts: webservers
  remote_user: "{{ hosts_remote_user }}"
  become: yes

  vars:
    datadog_api_key: "{{ dd_api_key }}"
    datadog_site: us5.datadoghq.com
    http_check:
        init_config:
        datadog_config:
          cmd_port: 5011
        datadog_checks:
          http_check:
            init_config:
            instances:
              - name: Site available
                url: "{{ host_url }}"
                tls_verify: true

  roles:
    - { role: datadog.datadog, become: yes }