- hosts: all
  remote_user: "{{ hosts_remote_user }}"
  
  roles:
    - { role: geerlingguy.pip, become: yes }
  
  tasks:
    - name: Copy env
      ansible.builtin.template:
        src: .env.j2
        dest: .env
        mode: 0644

    - name: Run app
      community.docker.docker_container:
        name: redmine_app
        image: redmine:5.0.5
        published_ports:
          - "{{ app_port }}:3000"
        restart_policy: always
        env_file: .env

- hosts: webservers
  remote_user: "{{ hosts_remote_user }}"
  become: yes
  roles:
    - { role: datadog.datadog, become: yes }